const state={config:null,products:[],selected:null,adminData:null};
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const money=(n)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const date=(v)=>v?new Date(typeof v==='number'?v:v.replace?.(' WIB','')).toLocaleString('id-ID'):'—';
const esc=(s)=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Permintaan gagal');return data}
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3500)}
async function boot(){try{state.config=await api('/api/config');$('#storeName').textContent=state.config.storeName;updateAuth();await loadCatalog()}catch(e){toast(e.message,true)}}
function updateAuth(){const a=state.config?.auth;$('#authButton').textContent=a?`${a.role==='admin'?'Admin':'@'+a.username} • Keluar`:'Masuk via Telegram';if(a?.role==='admin'){showAdmin()}else{$('#adminLogin').classList.remove('hidden');$('#adminDashboard').classList.add('hidden')}}
async function loadCatalog(){const d=await api('/api/catalog');state.products=d.products;$('#heroStock').textContent=d.products.flatMap(p=>p.variants).reduce((s,v)=>s+v.stock,0);$('#productGrid').innerHTML=d.products.length?d.products.map(productCard).join(''):'<div class="loading">Belum ada produk.</div>';$$('.variant').forEach(b=>b.onclick=()=>checkout(b.dataset.product,b.dataset.variant));}
function productCard(p){const stock=p.variants.reduce((s,v)=>s+v.stock,0);return `<article class="product"><div class="product-top"><div class="product-icon">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="">`:esc((p.name||'?')[0])}</div><span class="stock-pill ${stock?'':'out'}">${stock?stock+' READY':'HABIS'}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.desc||'Produk digital dengan pengiriman otomatis.')}</p><div class="variants">${p.variants.map(v=>`<button class="variant" data-product="${esc(p.id)}" data-variant="${esc(v.name)}" ${v.stock?'':'disabled'}><span>${esc(v.name)} <small>• ${v.stock} stok</small></span><span>${v.onSale?`<span class="old-price">${money(v.price)}</span><br>`:''}<b class="price">${money(v.finalPrice)}</b></span></button>`).join('')}</div></article>`}
function checkout(pid,vname){const p=state.products.find(x=>String(x.id)===String(pid)),v=p?.variants.find(x=>x.name===vname);if(!state.config.auth||state.config.auth.role!=='user'){openLogin();toast('Hubungkan Telegram sebelum checkout');return}state.selected={p,v};$('#checkoutBody').innerHTML=`<p class="eyebrow">CHECKOUT</p><h2>${esc(p.name)}</h2><p>${esc(v.name)} • <b class="price">${money(v.finalPrice)}</b> / akun</p><form id="checkoutForm" class="stack"><label>Jumlah<input id="checkoutQty" type="number" min="1" max="${v.stock}" value="1"></label><div id="checkoutTotal" class="metric"><strong>${money(v.finalPrice)}</strong><span>Total pembayaran</span></div><button class="primary">Buat QRIS</button></form>`;$('#checkoutQty').oninput=e=>$('#checkoutTotal strong').textContent=money(v.finalPrice*Number(e.target.value||0));$('#checkoutForm').onsubmit=createOrder;$('#checkoutDialog').showModal()}
async function createOrder(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const o=await api('/api/orders',{method:'POST',body:JSON.stringify({productId:state.selected.p.id,variant:state.selected.v.name,qty:Number($('#checkoutQty').value)})});$('#checkoutBody').innerHTML=`<div class="qr-wrap"><p class="eyebrow">MENUNGGU PEMBAYARAN</p><h2>Scan QRIS</h2><img src="${esc(o.qr_url)}" alt="QRIS"><div class="timer">Total ${money(o.total_amount)}</div><p>ID: <b>${esc(o.refId)}</b></p><p>Setelah lunas, akun otomatis dikirim ke Telegram kamu.</p><button class="primary" id="viewOrders">Lihat status pesanan</button></div>`;$('#viewOrders').onclick=()=>{$('#checkoutDialog').close();switchView('orders')}}catch(err){toast(err.message,true);btn.disabled=false}}
function openLogin(){$('#loginStepId').classList.remove('hidden');$('#loginStepOtp').classList.add('hidden');$('#loginDialog').showModal()}
async function loadOrders(){const box=$('#ordersContent');if(state.config.auth?.role!=='user'){box.className='panel empty-state';box.textContent='Masuk via Telegram untuk melihat pesanan web kamu.';return}try{const d=await api('/api/orders');box.className='panel';box.innerHTML=d.orders.length?d.orders.map(o=>`<div class="order-card"><div><h3>${esc(o.variant||'Pesanan digital')}</h3><p>${esc(o.referenceId)} • x${o.qty} • ${money(o.amount)}</p><p>${date(o.createdAt)}</p></div><div><span class="status ${esc(String(o.status).toLowerCase())}">${esc(o.status)}</span>${String(o.status).toLowerCase()==='pending'?`<br>${o.qrUrl?`<button class="outline show-qr" data-qr="${esc(o.qrUrl)}" data-ref="${esc(o.referenceId)}" data-amount="${o.amount}">Lihat QRIS</button>`:''}<button class="danger-btn cancel-order" data-id="${o.id}">Batalkan</button>`:''}</div></div>`).join(''):'<div class="empty-state">Belum ada pesanan web.</div>';$$('.cancel-order').forEach(b=>b.onclick=async()=>{if(!confirm('Batalkan pesanan ini?'))return;try{await api(`/api/orders/${b.dataset.id}/cancel`,{method:'POST'});toast('Pesanan dibatalkan');loadOrders();loadCatalog()}catch(e){toast(e.message,true)}});$$('.show-qr').forEach(b=>b.onclick=()=>{$('#checkoutBody').innerHTML=`<div class="qr-wrap"><p class="eyebrow">MENUNGGU PEMBAYARAN</p><h2>Scan QRIS</h2><img src="${b.dataset.qr}" alt="QRIS"><div class="timer">Total ${money(b.dataset.amount)}</div><p>ID: <b>${esc(b.dataset.ref)}</b></p><p>Setelah lunas, akun otomatis dikirim ke Telegram kamu.</p></div>`;$('#checkoutDialog').showModal()})}catch(e){box.textContent=e.message}}
async function showAdmin(){if(state.config.auth?.role!=='admin')return;$('#adminLogin').classList.add('hidden');$('#adminDashboard').classList.remove('hidden');await loadAdmin()}
async function loadAdmin(){try{const d=await api('/api/admin/overview');state.adminData=d;const vals=[['Produk',d.stats.products],['Stok real',d.stats.stock],['Pengguna',d.stats.users],['Omzet',money(d.stats.revenue)]];$('#stats').innerHTML=vals.map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('#stockProduct').innerHTML=d.products.map(p=>`<option value="${p.id}">${esc(p.name)} [${esc(p.code)}]</option>`).join('');syncVariants();$('#inventoryTable').innerHTML=table(['Produk / kode','Varian','Tersedia','Real','Pending'],d.products.flatMap(p=>p.variants.map(v=>[`${esc(p.name)}<br><small>${esc(p.code)}</small>`,esc(v.name),v.stock,v.realStock,v.reserved])));$('#transactionTable').innerHTML=table(['ID','User','Varian','Qty','Total','Metode','Status','Sumber'],d.transactions.map(t=>[esc(t.referenceId),esc(t.username||t.userId),esc(t.variant),t.qty,money(t.amount),esc(t.method),`<span class="status ${esc(String(t.status).toLowerCase())}">${esc(t.status)}</span>`,esc(t.source)]))}catch(e){toast(e.message,true)}}
function table(head,rows){return `<table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function syncVariants(){const p=state.adminData?.products.find(x=>String(x.id)===$('#stockProduct').value);$('#stockVariant').innerHTML=(p?.variants||[]).map(v=>`<option>${esc(v.name)}</option>`).join('')}
function switchView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$(`#${name}View`).classList.remove('hidden');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='orders')loadOrders();if(name==='admin'&&state.config.auth?.role==='admin')showAdmin()}
$$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('[data-scroll]').onclick=()=>$('#catalog').scrollIntoView();$('#refreshCatalog').onclick=()=>loadCatalog().then(()=>toast('Katalog diperbarui'));$('#authButton').onclick=async()=>{if(state.config.auth){await api('/api/auth/logout',{method:'POST'});state.config.auth=null;updateAuth();switchView('store');toast('Berhasil keluar')}else openLogin()};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#requestOtpForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/telegram/request',{method:'POST',body:JSON.stringify({userId:$('#telegramId').value})});$('#loginStepId').classList.add('hidden');$('#loginStepOtp').classList.remove('hidden');toast('Kode dikirim ke Telegram')}catch(x){toast(x.message,true)}};$('#verifyOtpForm').onsubmit=async e=>{e.preventDefault();try{await api('/api/auth/telegram/verify',{method:'POST',body:JSON.stringify({userId:$('#telegramId').value,code:$('#otpCode').value})});state.config=(await api('/api/config'));updateAuth();$('#loginDialog').close();toast('Telegram terhubung')}catch(x){toast(x.message,true)}};$('#backOtp').onclick=()=>{$('#loginStepId').classList.remove('hidden');$('#loginStepOtp').classList.add('hidden')};$('#adminTelegramLogin').onclick=async()=>{if(state.config.auth){await api('/api/auth/logout',{method:'POST'});state.config.auth=null;updateAuth()}openLogin()};$('#stockProduct').onchange=syncVariants;$('#stockForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const d=await api('/api/admin/stock',{method:'POST',body:JSON.stringify({productId:$('#stockProduct').value,variant:$('#stockVariant').value,stock:$('#stockData').value})});toast(`${d.added} akun ditambahkan${d.duplicates.length?`, ${d.duplicates.length} duplikat dilewati`:''}`);$('#stockData').value='';await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}finally{btn.disabled=false}};$('#refreshAdmin').onclick=loadAdmin;setInterval(()=>{if(!document.hidden){loadCatalog();if(!$('#ordersView').classList.contains('hidden'))loadOrders();if(state.config?.auth?.role==='admin'&&!$('#adminView').classList.contains('hidden'))loadAdmin()}},10000);boot();
