const state={config:null,products:[],selected:null,adminData:null,authMode:'login'};let loginPoll=null;
const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const money=(n)=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(n||0));
const date=(v)=>v?new Date(typeof v==='number'?v:v.replace?.(' WIB','')).toLocaleString('id-ID'):'—';
const esc=(s)=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(url,options={}){const r=await fetch(url,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Permintaan gagal');return data}
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className=`toast show${error?' error':''}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className='toast',3500)}
async function boot(){try{state.config=await api('/api/config');$('#storeName').textContent=state.config.storeName;updateAuth();await loadCatalog()}catch(e){$('#productGrid').innerHTML=`<div class="loading">Katalog gagal dimuat: ${esc(e.message)}<br><button class="outline" onclick="location.reload()">Muat ulang</button></div>`;toast(e.message,true)}}
function updateAuth(){const a=state.config?.auth;$('#authButton').textContent=a?`${a.email||a.username||'Akun'} • Keluar`:'Masuk / Daftar';if(a?.role==='admin'){showAdmin()}else{$('#adminLogin').classList.remove('hidden');$('#adminDashboard').classList.add('hidden')}}
function setAuthMode(mode){state.authMode=mode;$('#authTitle').textContent=mode==='register'?'Buat akun baru':'Masuk ke akun';$('#authSubtitle').textContent=mode==='register'?'Daftar dengan email. Tidak perlu Telegram untuk mulai order.':'Gunakan email untuk checkout dan menyimpan riwayat pesanan.';$('#firstNameField').classList.toggle('hidden',mode!=='register');$('#authSubmit').textContent=mode==='register'?'Daftar & mulai order':'Masuk';$$('.auth-tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.authMode===mode));$('#loginStatus').textContent='Akun web tidak wajib terhubung ke bot.'}
function openAccount(mode='login'){clearInterval(loginPoll);setAuthMode(mode);$('#loginDialog').showModal()}
async function submitAuth(event){event.preventDefault();const button=$('#authSubmit');button.disabled=true;try{const payload={email:$('#authEmail').value,password:$('#authPassword').value,firstName:$('#authFirstName').value};const result=await api(state.authMode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:JSON.stringify(payload)});state.config=await api('/api/config');updateAuth();$('#loginDialog').close();toast(state.authMode==='register'?'Akun berhasil dibuat':'Berhasil masuk');if(state.selected){const selected=state.selected;state.selected=null;checkout(selected.p.id,selected.v.name)}}catch(error){$('#loginStatus').textContent=error.message;toast(error.message,true)}finally{button.disabled=false}}
function openLogin(){openAccount('login')}
async function loadCatalog(){const d=await api('/api/catalog');state.products=d.products;$('#heroStock').textContent=d.products.flatMap(p=>p.variants).reduce((s,v)=>s+v.stock,0);$('#productGrid').innerHTML=d.products.length?d.products.map(productCard).join(''):'<div class="loading">Belum ada produk.</div>';$$('.variant').forEach(b=>b.onclick=()=>checkout(b.dataset.product,b.dataset.variant));}
function productCard(p){const stock=p.variants.reduce((s,v)=>s+v.stock,0);return `<article class="product"><div class="product-top"><div class="product-icon">${p.imageUrl?`<img src="${esc(p.imageUrl)}" alt="">`:esc((p.name||'?')[0])}</div><span class="stock-pill ${stock?'':'out'}">${stock?stock+' READY':'HABIS'}</span></div><h3>${esc(p.name)}</h3><p>${esc(p.desc||'Produk digital dengan pengiriman otomatis.')}</p><div class="variants">${p.variants.map(v=>`<button class="variant" data-product="${esc(p.id)}" data-variant="${esc(v.name)}" ${v.stock?'':'disabled'}><span>${esc(v.name)} <small>• ${v.stock} stok</small></span><span>${v.onSale?`<span class="old-price">${money(v.price)}</span><br>`:''}<b class="price">${money(v.finalPrice)}</b></span></button>`).join('')}</div></article>`}
function checkout(pid,vname){const p=state.products.find(x=>String(x.id)===String(pid)),v=p?.variants.find(x=>x.name===vname);if(!state.config.auth){state.selected={p,v};openLogin();toast('Masuk atau daftar untuk melanjutkan checkout');return}state.selected={p,v};$('#checkoutBody').innerHTML=`<p class="eyebrow">CHECKOUT</p><h2>${esc(p.name)}</h2><p>${esc(v.name)} • <b class="price">${money(v.finalPrice)}</b> / akun</p><form id="checkoutForm" class="stack"><label>Jumlah<input id="checkoutQty" type="number" min="1" max="${v.stock}" value="1"></label><div id="checkoutTotal" class="metric"><strong>${money(v.finalPrice)}</strong><span>Total pembayaran</span></div><button class="primary">Buat QRIS</button></form>`;$('#checkoutQty').oninput=e=>$('#checkoutTotal strong').textContent=money(v.finalPrice*Number(e.target.value||0));$('#checkoutForm').onsubmit=createOrder;$('#checkoutDialog').showModal()}
async function createOrder(e){e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const o=await api('/api/orders',{method:'POST',body:JSON.stringify({productId:state.selected.p.id,variant:state.selected.v.name,qty:Number($('#checkoutQty').value)})});$('#checkoutBody').innerHTML=`<div class="qr-wrap"><p class="eyebrow">MENUNGGU PEMBAYARAN</p><h2>Scan QRIS</h2><img src="${esc(o.qr_url)}" alt="QRIS"><div class="timer">Total ${money(o.total_amount)}</div><p>ID: <b>${esc(o.refId)}</b></p><p>Setelah lunas, detail produk akan muncul di riwayat pesanan. Jika akun Telegram terhubung, bot juga akan mengirim notifikasi.</p><button class="primary" id="viewOrders">Lihat status pesanan</button></div>`;$('#viewOrders').onclick=()=>{$('#checkoutDialog').close();switchView('orders')}}catch(err){toast(err.message,true);btn.disabled=false}}
async function openTelegramLogin(){clearInterval(loginPoll);if(!$('#loginDialog').open)$('#loginDialog').showModal();const link=$('#openTelegramLogin'),status=$('#loginStatus');link.classList.remove('hidden');link.textContent='Menyiapkan link…';link.removeAttribute('href');status.textContent='Setelah menekan Start di bot, kembali ke halaman ini.';try{const challenge=await api('/api/auth/telegram/link',{method:'POST'});link.href=challenge.url;link.textContent='Buka bot Telegram →';loginPoll=setInterval(async()=>{try{const result=await api(`/api/auth/telegram/status?token=${encodeURIComponent(challenge.token)}`);if(result.status!=='approved')return;clearInterval(loginPoll);state.config=await api('/api/config');updateAuth();$('#loginDialog').close();toast(result.role==='admin'?'Login admin berhasil':'Telegram berhasil terhubung');if(result.role==='admin')switchView('admin')}catch(error){if(error.message.includes('kedaluwarsa')){clearInterval(loginPoll);status.textContent='Link login kedaluwarsa.'}}},1200)}catch(error){link.textContent='Gagal membuat link';status.textContent=error.message;toast(error.message,true)}}
async function loadOrders(){const box=$('#ordersContent');if(!state.config.auth){box.className='panel empty-state';box.innerHTML='Masuk atau daftar untuk melihat pesanan web kamu.<br><button class="primary" id="ordersLogin">Masuk sekarang</button>';$('#ordersLogin').onclick=openLogin;return}try{const d=await api('/api/orders');box.className='panel';box.innerHTML=d.orders.length?d.orders.map(o=>`<div class="order-card"><div><h3>${esc(o.variant||'Pesanan digital')}</h3><p>${esc(o.referenceId)} • x${o.qty} • ${money(o.amount)}</p><p>${date(o.createdAt)}</p></div><div><span class="status ${esc(String(o.status).toLowerCase())}">${esc(o.status)}</span>${String(o.status).toLowerCase()==='pending'?`<br>${o.qrUrl?`<button class="outline show-qr" data-qr="${esc(o.qrUrl)}" data-ref="${esc(o.referenceId)}" data-amount="${o.amount}">Lihat QRIS</button>`:''}<button class="danger-btn cancel-order" data-id="${o.id}">Batalkan</button>`:''}</div></div>`).join(''):'<div class="empty-state">Belum ada pesanan web.</div>';$$('.cancel-order').forEach(b=>b.onclick=async()=>{if(!confirm('Batalkan pesanan ini?'))return;try{await api(`/api/orders/${b.dataset.id}/cancel`,{method:'POST'});toast('Pesanan dibatalkan');loadOrders();loadCatalog()}catch(e){toast(e.message,true)}});$$('.show-qr').forEach(b=>b.onclick=()=>{$('#checkoutBody').innerHTML=`<div class="qr-wrap"><p class="eyebrow">MENUNGGU PEMBAYARAN</p><h2>Scan QRIS</h2><img src="${b.dataset.qr}" alt="QRIS"><div class="timer">Total ${money(b.dataset.amount)}</div><p>ID: <b>${esc(b.dataset.ref)}</b></p><p>Setelah lunas, detail produk akan muncul di riwayat pesanan. Jika akun Telegram terhubung, bot juga akan mengirim notifikasi.</p></div>`;$('#checkoutDialog').showModal()})}catch(e){box.textContent=e.message}}
async function showAdmin(){if(state.config.auth?.role!=='admin')return;$('#adminLogin').classList.add('hidden');$('#adminDashboard').classList.remove('hidden');await loadAdmin()}
async function loadAdmin(){try{const d=await api('/api/admin/overview');state.adminData=d;const vals=[['Produk',d.stats.products],['Stok real',d.stats.stock],['Pengguna',d.stats.users],['Omzet',money(d.stats.revenue)]];$('#stats').innerHTML=vals.map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');const opts=d.products.map(p=>`<option value="${p.id}">${esc(p.name)} [${esc(p.code)}]</option>`).join('');$('#stockProduct').innerHTML=opts;$('#variantProduct').innerHTML=opts;$('#manageProduct').innerHTML=`<option value="new">+ Produk baru</option>${opts}`;syncVariants();syncManagedProduct();syncManagedVariants();$('#inventoryTable').innerHTML=table(['Produk / kode','Varian','Tersedia','Real','Pending','Harga'],d.products.flatMap(p=>p.variants.map(v=>[`${esc(p.name)}<br><small>${esc(p.code)}</small>`,esc(v.name),v.stock,v.realStock,v.reserved,money(v.finalPrice)])));$('#transactionTable').innerHTML=table(['ID','User','Varian','Qty','Total','Metode','Status','Sumber'],d.transactions.map(t=>[esc(t.referenceId),esc(t.username||t.userId),esc(t.variant),t.qty,money(t.amount),esc(t.method),`<span class="status ${esc(String(t.status).toLowerCase())}">${esc(t.status)}</span>`,esc(t.source)]))}catch(e){toast(e.message,true)}}
function table(head,rows){return `<table><thead><tr>${head.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c??'—'}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function syncVariants(){const p=state.adminData?.products.find(x=>String(x.id)===$('#stockProduct').value);$('#stockVariant').innerHTML=(p?.variants||[]).map(v=>`<option>${esc(v.name)}</option>`).join('');$('#stockItems').innerHTML='<div class="empty-mini">Klik refresh untuk menampilkan akun.</div>'}
async function loadStockItems(){const box=$('#stockItems'),productId=$('#stockProduct').value,variant=$('#stockVariant').value;if(!productId||!variant){box.innerHTML='<div class="empty-mini">Produk atau varian belum tersedia.</div>';return}box.innerHTML='<div class="empty-mini">Memuat stok…</div>';try{const d=await api(`/api/admin/stock/items?productId=${encodeURIComponent(productId)}&variant=${encodeURIComponent(variant)}`);box.innerHTML=d.items.length?d.items.map(item=>`<div class="stock-item"><div><b>${esc(item.email)}</b><small>Password: ${esc(item.password)}${item.note?` • ${esc(item.note)}`:''}</small></div><button class="danger-btn delete-stock-item" data-key="${esc(item.key)}">Hapus</button></div>`).join(''):'<div class="empty-mini">Stok varian ini kosong.</div>';$$('.delete-stock-item').forEach(button=>button.onclick=async()=>{if(!confirm(`Hapus stok ${button.parentElement.querySelector('b').textContent}?`))return;try{await api('/api/admin/stock/item',{method:'DELETE',body:JSON.stringify({productId,variant,key:button.dataset.key})});toast('Stok tertentu berhasil dihapus');await Promise.all([loadStockItems(),loadCatalog()])}catch(error){toast(error.message,true)}})}catch(error){box.innerHTML=`<div class="empty-mini">${esc(error.message)}</div>`}}
function syncManagedProduct(){const id=$('#manageProduct').value,p=state.adminData?.products.find(x=>String(x.id)===id),fresh=id==='new'||!p;$('#productCode').disabled=!fresh;$('#productCode').value=fresh?'':p.code;$('#productName').value=fresh?'':p.name;$('#productDesc').value=fresh?'':p.desc;$('#productImage').value=fresh?'':(p.imageUrl||'');$('#productVariants').value=fresh?'':'';$('#newVariantsLabel').classList.toggle('hidden',!fresh);$('#deleteProduct').classList.toggle('hidden',fresh);$('#saveProduct').textContent=fresh?'Tambah produk':'Simpan perubahan'}
function syncManagedVariants(){const p=state.adminData?.products.find(x=>String(x.id)===$('#variantProduct').value),select=$('#manageVariant');select.innerHTML=`<option value="new">+ Varian baru</option>${(p?.variants||[]).map(v=>`<option value="${esc(v.name)}">${esc(v.name)}</option>`).join('')}`;syncVariantEditor()}
function syncVariantEditor(){const p=state.adminData?.products.find(x=>String(x.id)===$('#variantProduct').value),name=$('#manageVariant').value,v=p?.variants.find(x=>x.name===name),fresh=name==='new'||!v;$('#variantName').value=fresh?'':v.name;$('#variantPrice').value=fresh?'':v.price;$('#deleteVariant').classList.toggle('hidden',fresh)}
function switchView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$(`#${name}View`).classList.remove('hidden');$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='orders')loadOrders();if(name==='admin'&&state.config.auth?.role==='admin')showAdmin()}
$$('.nav-btn').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$('[data-view-action]').forEach(b=>b.onclick=()=>switchView(b.dataset.viewAction));$('[data-scroll]').onclick=()=>$('#catalog').scrollIntoView();$('#refreshCatalog').onclick=()=>loadCatalog().then(()=>toast('Katalog diperbarui'));$('#authButton').onclick=async()=>{if(state.config.auth){await api('/api/auth/logout',{method:'POST'});state.config.auth=null;updateAuth();switchView('store');toast('Berhasil keluar')}else openLogin()};$$('[data-auth-mode]').forEach(b=>b.onclick=()=>setAuthMode(b.dataset.authMode));$('#authForm').onsubmit=submitAuth;$('#telegramLoginSecondary').onclick=openTelegramLogin;$$('[data-close]').forEach(b=>b.onclick=()=>{if(b.closest('dialog').id==='loginDialog')clearInterval(loginPoll);b.closest('dialog').close()});$('#adminTelegramLogin').onclick=async()=>{if(state.config.auth){await api('/api/auth/logout',{method:'POST'});state.config.auth=null;updateAuth()}openTelegramLogin()};setAuthMode('login');
$('#manageProduct').onchange=syncManagedProduct;
$('#productForm').onsubmit=async e=>{e.preventDefault();const id=$('#manageProduct').value,creating=id==='new',variants=$('#productVariants').value.split(/\r?\n/).filter(Boolean).map(line=>{const [name,price]=line.split('|');return{name:name?.trim(),price:Number(price)}}),payload={code:$('#productCode').value,name:$('#productName').value,desc:$('#productDesc').value,imageUrl:$('#productImage').value,variants};try{await api(creating?'/api/admin/products':`/api/admin/products/${id}`,{method:creating?'POST':'PUT',body:JSON.stringify(payload)});toast(creating?'Produk ditambahkan':'Produk diperbarui');await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}};
$('#deleteProduct').onclick=async()=>{const id=$('#manageProduct').value;if(!confirm('Hapus produk beserta seluruh stoknya?'))return;try{await api(`/api/admin/products/${id}`,{method:'DELETE'});toast('Produk dihapus');await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}};
$('#variantProduct').onchange=syncManagedVariants;$('#manageVariant').onchange=syncVariantEditor;
$('#variantForm').onsubmit=async e=>{e.preventDefault();const pid=$('#variantProduct').value,old=$('#manageVariant').value,creating=old==='new',payload={name:$('#variantName').value,price:Number($('#variantPrice').value)};try{await api(creating?`/api/admin/products/${pid}/variants`:`/api/admin/products/${pid}/variants/${encodeURIComponent(old)}`,{method:creating?'POST':'PUT',body:JSON.stringify(payload)});toast(creating?'Varian ditambahkan':'Varian diperbarui');await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}};
$('#deleteVariant').onclick=async()=>{const pid=$('#variantProduct').value,name=$('#manageVariant').value;if(!confirm(`Hapus varian ${name} beserta stoknya?`))return;try{await api(`/api/admin/products/${pid}/variants/${encodeURIComponent(name)}`,{method:'DELETE'});toast('Varian dihapus');await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}};
$('#stockProduct').onchange=syncVariants;$('#stockVariant').onchange=()=>{$('#stockItems').innerHTML='<div class="empty-mini">Klik refresh untuk menampilkan akun.</div>'};$('#loadStockItems').onclick=loadStockItems;$('#stockForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;try{const d=await api('/api/admin/stock',{method:'POST',body:JSON.stringify({productId:$('#stockProduct').value,variant:$('#stockVariant').value,stock:$('#stockData').value})});toast(`${d.added} akun ditambahkan${d.duplicates.length?`, ${d.duplicates.length} duplikat dilewati`:''}`);$('#stockData').value='';await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}finally{btn.disabled=false}};
$('#removeStockForm').onsubmit=async e=>{e.preventDefault();if(!confirm('Kurangi stok paling lama (FIFO)?'))return;try{const d=await api('/api/admin/stock',{method:'DELETE',body:JSON.stringify({productId:$('#stockProduct').value,variant:$('#stockVariant').value,qty:Number($('#removeStockQty').value)})});toast(`${d.removed} stok dihapus`);$('#removeStockQty').value='';await Promise.all([loadAdmin(),loadCatalog()])}catch(x){toast(x.message,true)}};
$('#refreshAdmin').onclick=loadAdmin;setInterval(()=>{if(!document.hidden){loadCatalog();if(!$('#ordersView').classList.contains('hidden'))loadOrders()}},10000);boot();
